# The Linux desktop app is only published as a .deb in Anthropic's apt
# repository, so this unpacks the prebuilt Electron bundle. `sources.json`
# pins the pool URLs and is regenerated by ./update.sh — an apt index is
# nothing nix-update can read, so `just bump` does not work here.
{
  lib,
  stdenv,
  fetchurl,
  autoPatchelfHook,
  dpkg,
  makeWrapper,
  wrapGAppsHook3,
  alsa-lib,
  at-spi2-atk,
  at-spi2-core,
  cairo,
  cups,
  dbus,
  expat,
  gdk-pixbuf,
  glib,
  gtk3,
  libcap_ng,
  libdrm,
  libgbm,
  libglvnd,
  libnotify,
  libpulseaudio,
  libseccomp,
  libsecret,
  libuuid,
  libx11,
  libxcb,
  libxcomposite,
  libxdamage,
  libxext,
  libxfixes,
  libxkbcommon,
  libxrandr,
  libxshmfence,
  nspr,
  nss,
  pango,
  pipewire,
  systemdLibs,
  versionCheckHook,
  wayland,
  writableTmpDirAsHomeHook,
  xdg-utils,
}:
let
  sources = lib.importJSON ./sources.json;
  source =
    sources.platforms.${stdenv.hostPlatform.system}
      or (throw "claude-desktop: no package for ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  __structuredAttrs = true;
  strictDeps = true;

  pname = "claude-desktop";
  inherit (sources) version;

  src = fetchurl { inherit (source) url hash; };

  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
    makeWrapper
    wrapGAppsHook3
  ];

  buildInputs = [
    alsa-lib
    at-spi2-atk
    at-spi2-core
    cairo
    cups
    dbus
    expat
    gdk-pixbuf
    glib
    gtk3
    libcap_ng # resources/virtiofsd
    libdrm
    libgbm
    libseccomp # resources/virtiofsd
    libuuid
    libx11
    libxcb
    libxcomposite
    libxdamage
    libxext
    libxfixes
    libxkbcommon
    libxrandr
    libxshmfence
    nspr
    nss
    pango
    systemdLibs
  ];

  # dlopen()ed by Chromium, so they never show up as DT_NEEDED for
  # autoPatchelfHook to pick up on its own.
  runtimeDependencies = map lib.getLib [
    libglvnd
    libnotify
    libpulseaudio
    libsecret # credential storage
    pipewire # screen sharing
    wayland
  ];

  dontConfigure = true;
  dontBuild = true;
  # The Electron binary carries its own v8 snapshots and ASAR payload; leave it
  # exactly as shipped.
  dontStrip = true;
  # The launcher is wrapped by hand in preFixup, where gappsWrapperArgs is
  # already assembled, so that the flags land on it and not on the bundle's
  # internal binaries.
  dontWrapGApps = true;

  # chrome-sandbox ships setuid, which `dpkg -x` refuses to unpack.
  unpackPhase = ''
    runHook preUnpack

    dpkg-deb --fsys-tarfile $src | tar --extract --no-same-owner --no-same-permissions

    runHook postUnpack
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/lib $out/share
    cp -r usr/lib/claude-desktop $out/lib/
    cp -r usr/share/icons $out/share/
    install -Dm644 usr/share/applications/com.anthropic.Claude.desktop -t $out/share/applications

    substituteInPlace $out/share/applications/com.anthropic.Claude.desktop \
      --replace-fail "Exec=claude-desktop" "Exec=$out/bin/claude-desktop"

    runHook postInstall
  '';

  # Electron resolves `resources/` relative to the executable, so the launcher
  # has to be a wrapper rather than a symlink into $out/bin. Ozone is hinted
  # rather than forced: it picks Wayland when the session is Wayland and falls
  # back to X11 everywhere else.
  preFixup = ''
    makeWrapper $out/lib/claude-desktop/claude-desktop $out/bin/claude-desktop \
      "''${gappsWrapperArgs[@]}" \
      --suffix PATH : ${lib.makeBinPath [ xdg-utils ]} \
      --add-flags "--ozone-platform-hint=auto" \
      --add-flags "--enable-features=WaylandWindowDecorations" \
      --add-flags "--enable-wayland-ime=true"
  '';

  # Electron answers --version before it needs a display, which doubles as a
  # check that the unpacked bundle actually links against the store.
  doInstallCheck = true;
  nativeInstallCheckInputs = [
    versionCheckHook
    writableTmpDirAsHomeHook
  ];
  versionCheckKeepEnvironment = [ "HOME" ];
  versionCheckProgramArg = "--version";

  passthru.updateScript = ./update.sh;

  meta = {
    description = "Desktop application for Claude.ai";
    homepage = "https://claude.ai/download";
    downloadPage = "https://code.claude.com/docs/en/desktop-linux";
    license = lib.licenses.unfree;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
    platforms = builtins.attrNames sources.platforms;
    mainProgram = "claude-desktop";
  };
}
