name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
    - '**.nix'
    - '**.lock'
    - '.github/workflows/check.yml'

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - name: Check Flake
        run: nix flake check --accept-flake-config

  check-lock:
    name: Build Nix targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
