name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/check.yaml"

jobs:
  check-flake:
    name: Check Flake Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Check Flake
        # run: |
        #   NIXPKGS_ALLOW_INSECURE=1
        #   nix flake check
        #   --no-build
        #   --impure
        # --show-trace
        # run: NIXPKGS_ALLOW_INSECURE=1 nix flake check --no-build --accept-flake-config --impure
        run: NIXPKGS_ALLOW_INSECURE=1 nix flake check --accept-flake-config --impure
