name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/check.yaml"

jobs:
  check-lock:
    name: Check Lock
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main

  check-flake:
    name: Check Flake
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [check-lock]
    # strategy:
    #   fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-flake
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      # - name: Cache
      #   uses: DeterminateSystems/flakehub-cache-action@main
      - name: Flake Statistics
        run: |
          echo "# :clock5: Tokei Summary" >> $GITHUB_STEP_SUMMARY
          nix run nixpkgs#tokei -- -o json . | jq -r '
            # Header for the markdown table
            "| Language | Files | Code | Comments | Blanks |",
            "|---|---|---|---|---|",

            # Process each language
            (keys_unsorted | .[] | select(. != "Total")) as $lang |
            (.[$lang] | "| \($lang) | \(.reports | length) | \(.code) | \(.comments) | \(.blanks) |")
            ' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
      - name: Check Flake
        run: nix flake check --accept-flake-config
      # - name: Linting
      #   run: nix run nixpkgs#statix -- check

  # check-flake-debug:
  #   name: Check Flake (debug mode)
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   needs: [check-flake]
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         fetch-depth: 1
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #       with:
  #         logger: pretty
  #     - name: Cache
  #       uses: DeterminateSystems/flakehub-cache-action@main
  #     - name: Check Flake
  #       run: nix flake check --accept-flake-config --debug
